apiVersion: v1
kind: Namespace
metadata:
  name: trafficgen-shared-edge
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgen-shared-edge
  namespace: trafficgen-shared-edge
  labels:
    app: trafficgen-shared-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgen-shared-edge
  template:
    metadata:
      labels:
        app: trafficgen-shared-edge
    spec:
      containers:
        - name: trafficgen-shared-edge
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              export INGRESS_HOST_IP=48.216.196.66
              export INGRESS_HOST_NAME=shared.ngcom.dev.amshop.com
              while :; do
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comamshopas/proxy/comamshopbs/proxy/comamshopds"
                sleep 2
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comamshopas/proxy/comamshopbs/proxy/comcartas.cart-global-dev"
                sleep 2
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comamshopas/proxy/comamshopbs/proxy/comproductas.product-global-dev"
                sleep 2
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comamshopas/proxy/comamshopbs/proxy/compaymentas.payment-global-dev"
                sleep 2
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comcartas/proxy/comcartbs/proxy/comcartds"
                sleep 2
                curl -k -vvv -HHost:$INGRESS_HOST_NAME -H "X-B3-Sampled: 1" --resolve "$INGRESS_HOST_NAME:80:$INGRESS_HOST_IP" "http://${INGRESS_HOST_NAME}:80/comproductas/proxy/comproductbs/proxy/comproductds"
                sleep 2
              done
