---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: comproductbs
      namespace: product-global-dev
      labels:
        app: comproductbs
        service: comproductbs
    spec:
      ports:
        - port: 80
          targetPort: 8000
          name: http
        - port: 3000
          targetPort: 3000
          name: tcp
      selector:
        app: comproductbs
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sa-comproductbs
      namespace: product-global-dev
      labels:
        app: comproductbs
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: comproductbs-v1
      namespace: product-global-dev
      labels:
        app: comproductbs
        version: v1
    spec:
      selector:
        matchLabels:
          app: comproductbs
          version: v1
      template:
        metadata:
          labels:
            app: comproductbs
            version: v1
        spec:
          serviceAccountName: sa-comproductbs
          containers:
            - name: obs-tester
              image: gcr.io/timmers-images/obs-tester-server:v2.0
              imagePullPolicy: Always
              args:
                - '--log-output-level=all:debug'
                - '--http-listen-address=:8000' # address the http server in the container listens on
                - '--tcp-listen-address=:3000' # address the tcp server in the container listens on
                - '--ep-duration=0' # the default latency used for handling requests to / (echo handler)
                - '--ep-errors=0' # the default percentage of errors injected when handling echo requests
                - '--ep-headers=0' # the default percentage of double headers injected when handling echo requests
                - '--zipkin-reporter-endpoint=http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans'
                - '--zipkin-sample-rate=1.0' # When we originate client request, this is the sample rate we use.
                - '--zipkin-singlehost-spans' # Envoy does not work well with Zipkin's default shared spans
              env:
                - name: SVCNAME
                  value: comproductbs
              ports:
                - name: http
                  containerPort: 8000
                - name: tcp
                  containerPort: 3000
