apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: user-reader
spec:
  displayName: User Reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Team
      - User
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: cluster-reader
spec:
  displayName: Cluster Reader
  fqn: rbac/cluster-reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Cluster
      - Organization
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: tenant-reader
spec:
  displayName: Tenant Reader
  fqn: rbac/tenant-reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Tenant
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: OrganizationAccessBindings
metadata:
  organization: tetrate
  name: tetrate
spec:
  allow:
  - role: rbac/registryreader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/user-reader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/cluster-reader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/admin
    subjects:
    - serviceAccount: teamsync-job
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: TenantAccessBindings
metadata:
  organization: tetrate
  tenant: eshop
  name: eshop
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: admin
  - role: rbac/creator
    subjects:
    - user: organizations/tetrate/users/${TENANT_OWNER}
  - role: rbac/tenant-reader
    subjects:
    - team: organizations/tetrate/teams/eshop-team
    - team: organizations/tetrate/teams/payments-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: WorkspaceAccessBindings
metadata:
  organization: tetrate
  tenant: eshop
  workspace: payments
  name: payments
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${TENANT_OWNER}
  - role: rbac/creator
    subjects:
    - team: organizations/tetrate/teams/payments-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: WorkspaceAccessBindings
metadata:
  organization: tetrate
  tenant: eshop
  workspace: eshop
  name: eshop
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${TENANT_OWNER}
  - role: rbac/creator
    subjects:
    - team: organizations/tetrate/teams/eshop-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: GatewayAccessBindings
metadata:
  organization: tetrate
  tenant: eshop
  workspace: payments
  group: payments-gateways
  name: payments-gateways
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${PAYMENTS_OWNER}
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: GatewayAccessBindings
metadata:
  organization: tetrate
  tenant: eshop
  workspace: eshop
  group: eshop-gateways
  name: eshop-gateways
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${ESHOP_OWNER}
