apiVersion: tsb.tetrate.io/v2
kind: OrganizationSetting
metadata:
  name: tetrate-settings
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  networkSettings:
    networkReachability:
      tier1: aks,eks
      # aks: eks
      # eks: aks
  defaultSecuritySetting:
    authenticationSettings:
      trafficMode: OPTIONAL
    authorization:
      mode: DISABLED
    description: Default security settings for the org
    displayName: default-security-settings
  defaultTrafficSetting:
    description: Default traffic settings for the org
    displayName: default-traffic-settings
    reachability:
      mode: CLUSTER
    resilience:
      circuitBreakerSensitivity: LOW
      httpRequestTimeout: 3s
      httpRetries:
        attempts: 2
        perTryTimeout: 3s
        retryOn: 5xx