---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: demo-nonprod
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Demo Non-Prod
      displayName: Demo Non-prod
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: demo-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: demo-nonprod
    spec:
      namespaceSelector:
        names:
          - "*/demo-apps"
          - "*/demo-tester"
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: demo-prod
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Demo Prod
      displayName: Demo Prod
