apiVersion: tsb.tetrate.io/v2
kind: OrganizationSetting
metadata:
  name: tetrate-settings
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  networkSettings:
    networkReachability:
      tier1: aks,eks
      # aks: eks
      # eks: aks
