apiVersion: v1
kind: Namespace
metadata:
  name: trafficgen-payment-dev
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgen-payment-dev
  namespace: trafficgen-payment-dev
  labels:
    app: trafficgen-payment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgen-payment-dev
  template:
    metadata:
      labels:
        app: trafficgen-payment-dev
    spec:
      containers:
        - name: trafficgen-payment-dev
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              export INGRESS_HOST=48.216.193.244
              while :; do
                curl -k -vvv -HHost:internal.compaymentas.tetrate.io -H "X-B3-Sampled: 1" --resolve "internal.compaymentas.tetrate.io:80:$INGRESS_HOST" "http://internal.compaymentas.tetrate.io:80/proxy/compaymentbs/proxy/compaymentds"
                sleep 6
              done
