apiVersion: v1
kind: Namespace
metadata:
  name: trafficgen-amshop-dev
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgen-amshop-dev
  namespace: trafficgen-amshop-dev
  labels:
    app: trafficgen-amshop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgen-amshop-dev
  template:
    metadata:
      labels:
        app: trafficgen-amshop-dev
    spec:
      containers:
        - name: trafficgen-amshop-dev
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              while :; do
                curl -k -vvv -H "X-B3-Sampled: 1" "http://comamshopas.amshop-global-dev/proxy/comproductas.product-global-dev"
                curl -k -vvv -H "X-B3-Sampled: 1" "http://comamshopas.amshop-global-dev/proxy/comcartas.cart-global-dev"
                curl -k -vvv -H "X-B3-Sampled: 1" "http://comamshopas.amshop-global-dev/proxy/compaymentas.payment-global-dev"
                sleep 6
              done
