---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: global-dev
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Global Products Dev
      displayName: Global Products Dev
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: payment-global-dev-ws
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/payment-global-dev"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: payment-global-dev-gg
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
        tsb.tetrate.io/workspace: payment-global-dev-ws
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/payment-global-dev"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: payment-global-dev-tg
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
        tsb.tetrate.io/workspace: payment-global-dev-ws
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/payment-global-dev"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: payment-global-dev-sg
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
        tsb.tetrate.io/workspace: payment-global-dev-ws
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/payment-global-dev"
      configMode: BRIDGED
  - apiVersion: istiointernal.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: payment-global-dev-ig
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
        tsb.tetrate.io/workspace: payment-global-dev-ws
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/payment-global-dev"
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: cart-global-dev-ws
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/cart-global-dev"
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: product-global-dev-ws
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/product-global-dev"
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: amshop-global-dev-ws
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/amshop-global-dev"
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: app-gateways-global-dev-ws
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/app-gateways-global-dev"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: app-gateways-global-dev-gg
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: global-dev
        tsb.tetrate.io/workspace: app-gateways-global-dev-ws
    spec:
      namespaceSelector:
        names:
          - "ngcom-preprod01-tier2-blue/app-gateways-global-dev"
      configMode: BRIDGED
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: global-qa
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Global Products QA
      displayName: Global Products QA
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: global-prod
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Global Products Prod
      displayName: Global Products Prod
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: global-perf
      namespace: tsb-gitops
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: Global Products Perf
      displayName: Global Products Perf
