---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: demo-nonprod
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: demo-nonprod
      displayName: demo-nonprod
  # - apiVersion: tsb.tetrate.io/v2
  #   kind: Tenant
  #   metadata:
  #     name: demo-prod
  #     annotations:
  #       tsb.tetrate.io/organization: tetrate
  #   spec:
  #     description: demo-prod
  #     displayName: demo-prod
