---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amshop-platform
  namespace: argocd
spec:
  destination:
    namespace: tsb
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/amshop/platform
    repoURL: https://github.com/timmers-io/tsb-demo-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 1m # the maximum amount of time allowed for the backoff strategy
