apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  organization: tetrate
  name: obstest
spec:
  displayName: Observability Test Services
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: obstest
  name: obstest-ws
spec:
  displayName: obstest-ws
  namespaceSelector:
    names:
      - "az-services-cp19/obstest"
      - "az-services-cp19/egress"
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: obstest
  workspace: obstest-ws
  name: obstest-tg
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
      - "az-services-cp19/obstest"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: obstest
  workspace: obstest-ws
  name: obstest-gg
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
      - "az-services-cp19/obstest"
      - "az-services-cp19/egress"
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: obstest
  workspace: obstest-ws
  name: obstest-sg
spec:
  configMode: BRIDGED
  namespaceSelector:
    names:
      - "az-services-cp19/obstest"
---
apiVersion: istiointernal.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: obstest
  workspace: obstest-ws
  name: obstest-ig
spec:
  namespaceSelector:
    names:
      - "az-services-cp19/obstest"
      - "az-services-cp19/egress"
