apiVersion: traffic.tsb.tetrate.io/v2
kind: ServiceRoute
metadata:
  organization: tetrate
  tenant: obstest
  workspace: obstest-ws
  group: obstest-tg
  name: svcc-service-route
spec:
  service: obstest/svcc.obstest.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
      weight: 100